### ISSUE TITLE
Preparing metadata (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by aceladines** [glitzflitz/pyxorfilter#11]
Tried installing it on py version 3.12 (latest) got and error about metadata. Any workaround here?

**Comment by aceladines** [comment]
Collecting pyxorfilter
  Using cached pyxorfilter-1.0.0.tar.gz (9.1 kB)
  ...
  FileNotFoundError: [Errno 2] No such file or directory: 'lib/xor_singleheader/include/xorfilter.h'
  ...
  Encountered error while generating package metadata.

**Comment by glitzflitz** [comment]
Released the new version on https://pypi.org/project/pyxorfilter. You should be able to install with latest python 3.12 now.
