### ISSUE TITLE
Fresh context data deserialization failure

### ISSUE THREAD

**Issue by pedramamini** [glitzflitz/pyxorfilter#17]
Building on #14 ... the serialized data on disk looks far better. However, deserialization doesn't seem to be working correctly if attempted from a fresh process. Let me explain further with some code:

```
            needle = data_list[-1]

            assert needle in iocs
            print(f"[PASS] assert {needle} in data_list")

            assert xorf.contains(needle)
            print(f"[PASS] assert xorf.contains({needle})")

            with open(local_path, "wb+") as fh:
                fh.write(xorf_data)

            with open(local_path, "rb") as fh:
                deserialized_xor = pyxorfilter.Fuse16.deserialize(fh.read())

            assert deserialized_xor.contains(needle)
            print(f"[PASS] assert deserialized_xor.contains({needle})")

            del(deserialized_xor)
```

The above code passes all assertions without fail. However, try this from another process:

```
            with open(local_path, "rb") as fh:
                deserialized_xor = pyxorfilter.Fuse16.deserialize(fh.read())
            assert deserialized_xor.contains("EXPECTED VALUE")
```

This will fail.  None of the expected values are found in the deserialized xorfilter from a fresh context.

**Comment by kng7777** [comment]
> Building on #14 ... the serialized data on disk looks far better. However, deserialization doesn't seem to be working correctly if attempted from a fresh process. Let me explain further with some code:
> 
> ```
>             needle = data_list[-1]
> 
>             assert needle in iocs
>             print(f"[PASS] assert {needle} in data_list")
> 
>             assert xorf.contains(needle)
>             print(f"[PASS] assert xorf.contains({needle})")
> 
>             with open(local_path, "wb+") as fh:
>                 fh.write(xorf_data)
> 
>             with open(local_path, "rb") as fh:
>                 deserialized_xor = pyxorfilter.Fuse16.deserialize(fh.read())
> 
>             assert deserialized_xor.contains(needle)
>             print(f"[PASS] assert deserialized_xor.contains({needle})")
> 
>             del(deserialized_xor)
> ```
> 
> The above code passes all assertions without fail. However, try this from another process:
> 
> ```
>             with open(local_path, "rb") as fh:
>                 deserialized_xor = pyxorfilter.Fuse16.deserialize(fh.read())
>             assert deserialized_xor.contains("EXPECTED VALUE")
> ```
> 
> This will fail. None of the expected values are found in the deserialized xorfilter from a fresh context.

I had check on version 1.1.0 in before and problem the same with your.

**Comment by pedramamini** [comment]
@lemire one more hangup on deserialization

**Comment by lemire** [comment]
Let us see what we can do.

**Comment by lemire** [comment]
Ok. So far I have verified the problem, but I am puzzled. The right data gets saved to the file. When you pull it back, you do get the same data as in the original process. So it *should* work. It is unexpected that it fails.

Probably some small issue I missed.

**Comment by lemire** [comment]
Ah. The problem is not with the serialization and deserialization. But rather with the hashing. Python uses random hashing.

**Comment by lemire** [comment]
See https://github.com/glitzflitz/pyxorfilter/pull/18/files

**Comment by pedramamini** [comment]
Aha... thank you for that root cause analysis!

**Comment by glitzflitz** [comment]
Thank you @pedramamini for reporting the bug and @lemire for fixing! Sorry for the delay
