### ISSUE TITLE
Handling Duplicate Keys

### ISSUE THREAD

**Issue by felix-gohla** [glitzflitz/pyxorfilter#6]
Hi and first at all thank you for providing this python wrapper!

During some tests, I noticed, that the python process hangs during populating the XOR-filter when using duplicate items.
I found, that the upstream library now provides the feedback to the user when duplicate keys are recognised.

Now, I wanted to ask whether we could do the following:

- Update the upstream `xor_singleheader` library via the submodule.
- Allow the user to automatically de-duplicate the entries before population.

If you're fine with this, I'd be glad to contribute and issue the corresponding pull requests. 😊 🚀

**Comment by lemire** [comment]
I have issued PR that should fix this issue.

**Comment by lemire** [comment]
We no longer fail when given duplicated values.
