### ISSUE TITLE
python 3.10 support, can't install via PIP

### ISSUE THREAD

**Issue by vshuraeff** [glitzflitz/pyxorfilter#7]
hi! I cant install via pip for Python 3.10
```bash
$ pip install pyxorfilter
ERROR: Could not find a version that satisfies the requirement pyxorfilter (from versions: none)
ERROR: No matching distribution found for pyxorfilter
```

```bash
$ pip --version
pip 22.2
```

```bash
$ python --version
Python 3.10.5
```

**Comment by lemire** [comment]
Here are the prebuilt binaries:

https://pypi.org/project/pyxorfilter/#files

I am not the maintainer of this project, but if your system is not covered by these binaries, you may need to build it from source. Or the maintainer could extend support to other platform. To help the maintainer, you may want to specify your platform.

**Comment by glitzflitz** [comment]
If you are on windows or mac, you will have to build the package locally. I need to figure out how to set up CI to build binaries for windows and mac

**Comment by glitzflitz** [comment]
Released new version on PyPI which should have wheels for newer version of python. 
https://pypi.org/project/pyxorfilter/#files
Closing the issue.
